# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e257d2da2bda56cae5a0caec4d9d30adb9e43be044191bdd651a2108753589d8d0c31ba7332899521c8dee3497aa52187da5604358a159e7341be876dac5ea8

test:
  secret_key_base: da569d0bed10253132bbdc03c5d07e33b165add43f307e322df026cdb2fc3c186194dbde216759b4ec0ffb835fd80cba3e6a640c5d4b0c6d4d23be544125eb02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
